### ISSUE TITLE
very very large MP4 Files

### ISSUE THREAD

**Issue by Stefan1286b** [ispysoftware/iSpy#43] opened 2018-01-10 17:01 UTC
ISpy 6.9.0.0 Win64
ISpy saves very very large MP4 Files.
7 Camera every camera in ISpy has a record MP4 File with ~26 GiB
File Date is First Motion after restart Ispy.
Max. Record Time = 900s
CPU ~ 90%
RAM ~ GiB
It seems that Max. Record Time has no effect.
Grid View Feeze

**Comment by ispysoftware** [comment] 2018-01-11 00:18
Can you give me steps to reproduce and settings?

**Comment by Stefan1286b** [comment] 2018-01-11 16:41
Just Run iSpy
[config.xml.txt](https://github.com/ispysoftware/iSpy/files/1623345/config.xml.txt)
[objects.xml.txt](https://github.com/ispysoftware/iSpy/files/1623346/objects.xml.txt)

**Comment by ispysoftware** [comment] 2018-01-11 23:54
Can you try closing the grid view?

**Comment by ispysoftware** [comment] 2018-01-12 01:29
The problem with the grid view freezing is that your PC is running out of
CPU resources. iSpy only redraws the grid view when the app isn't busy
processing video and writing files. I'm not sure why it's creating massive
files though - repro'd it here and it looks like it's only happening when
recording multiple cameras with a fullscreen grid view - pretty weird!

**Comment by Stefan1286b** [comment] 2018-01-12 07:54
I Deleted the Gridviews and all is fine.

**Comment by Stefan1286b** [comment] 2018-01-12 07:57
But I need the GridView. On another Computer I have the same Problem and I have 2 GridViews

**Comment by ispysoftware** [comment] 2018-01-12 08:01
need to figure out it it's a cpu related thing or a grid view related thing
- try with just a couple of cameras running and see if you can reproduce
the issue

**Comment by Stefan1286b** [comment] 2018-01-12 11:49
I've reduce the nums of camera to 4 and to 2.
With GridView it is the same problem. Files are very large ~30GiB after some hours.
Without Gridview all fine.

**Comment by ispysoftware** [comment] 2018-01-12 23:20
Can you check the ispy log file? (view - log file)

**Comment by Stefan1286b** [comment] 2018-01-16 06:59
I've looked in the LogFile everytime. There wasn't any kind of warnings.
I'm not able to post Logfile in the next 4 weeks. I'm not at the Location. The Computer has no Internet Connection. I've planned to be there in 4 weeks. And Everyone hope to solve the problem at this Time.

**Comment by ispysoftware** [comment] 2018-01-16 08:21
Hi Stefan, Have you downloaded the source code and tried to figure out the
issue yourself? I'm unable to reproduce it here and have not had any other
reports of it happening...

**Comment by marcel03** [comment] 2018-02-14 10:47
Hi, I have same issue with versions 6.8.2, 6.9.0, 6.9.8. I tried 6.9.8 today and same issue. All cameras have MJPEG source. Last working version is 6.5.8 for me. 
From few minutes to 1-2 hours ispy freezes and starts to write file/files until I kill the process. I tried to switch cameras from MJPEG to RTSP source but same issue came few minutes after start.

**Comment by ispysoftware** [comment] 2018-02-14 12:14
can you check the log file for errors (view - log file)

**Comment by marcel03** [comment] 2018-02-14 12:40
Part of Log: 
Log Start (v6.9.8.0 Platform: x64): 14. 2. 2018 11:11:32
....
3x Error | 11:19:32 | Vratnica: Skipped recording - maximum recording thread limit hit. See settings to modify the limit.
Exception: | 11:19:32 | MJPEG: Connection failedConnection failedi SpyApplication.Sources.Video.MJPEGStream.WorkerThread()System.Collections.ListDictionaryInternal
Message | 11:19:32 | Reconnecting 1. Poschodie - Schody in 2s
Error | 11:19:32 | 1. Poschodie - Schody: Device Lost
25x Error | 11:19:32 | Vratnica: Skipped recording - maximum recording thread limit hit. See settings to modify the limit.
( ALL CAMERAS ) 
Message | 11:20:25 | Reconnecting 2. Poschodie in 2s
Error | 11:20:25 | 2. Poschodie: Device Lost

All Grids were frozen. 

After this I reinstaled v6.5.8.0 Platform: x64 and everything is OK. Configuration of all cameras is same.

**Comment by ispysoftware** [comment] 2018-02-14 12:46
Can you try it without the grid showing?

**Closed** 2018-09-04 08:49 UTC
