### ISSUE TITLE
api: getcontentlist doesn't work

### ISSUE THREAD

**Issue by Jessicayanhu** [ispysoftware/iSpy#108] opened 2020-05-11 06:44 UTC
I try to use "getcontentlist" to get some record file list, but seems the api doesn't work, it only returns "iSpy server is running", I wonder how it will work.

I want to visit this url to get the file list:
http://***/getcontentlist?ot=2&oid=1&page=0&startdate=1&enddate=1589162799&pagesize=20&ordermode=1

I set startdate as 1 and enddate as today's timestamp, but only returns "iSpy server is running", could you please help me to find what the problem is? Thank you.

**Comment by ispysoftware** [comment] 2020-05-11 10:56
I think it's because there are no files

**Comment by Jessicayanhu** [comment] 2020-05-12 00:54
I use below url to play a mp4 file, it works fine, I think the file exists, how it could be?
http://***/playfile?ot=2&oid=1&fn=1_2020-05-09_14-17-16.mp4

**Comment by ispysoftware** [comment] 2020-05-12 01:14
Actually, looking into it further, your enddate isn't a valid dotnet ticks
number. Should be around 637202179161567896
- try it without an enddate in the query
getcontentlist?ot=2&oid=1&page=0&startdate=1&pagesize=20&ordermode=1

**Comment by Jessicayanhu** [comment] 2020-05-12 01:36
I tried this query:
getcontentlist?ot=2&oid=1&page=0&startdate=1&pagesize=20&ordermode=1

it returns below reponse:
{"server":"iSpy","error":"Authentication failed","errorType":"authentication"}

maybe because I am not a subscriber, just a trial?
but if so, why could this url:  "http://***/playfile?ot=2&oid=1&fn=1_2020-05-11_17-27-37.mp4" works fine?

**Comment by ispysoftware** [comment] 2020-05-12 01:43
you're getting that error because your IP hasn't been whitelisted - add
your local IP address into IP Access in iSpy settings.
PlayFile is excepted for local playback

**Comment by Jessicayanhu** [comment] 2020-05-12 01:58
I try to add ".*" in IP Access setting page，but it still returns the error message.

![error message](https://user-images.githubusercontent.com/36437379/81630025-1c789c80-9437-11ea-81bf-015a9f916d43.png)

**Comment by ispysoftware** [comment] 2020-05-12 02:00
just add your local IP address
like
192.168.1.1

**Comment by Jessicayanhu** [comment] 2020-05-12 02:25
Add my ip address in IP access setting, and enter still doesn't work...
![ip address 1](https://user-images.githubusercontent.com/36437379/81631390-54cdaa00-943a-11ea-8298-dcef24eef044.png)
![ip address](https://user-images.githubusercontent.com/36437379/81631393-58613100-943a-11ea-8d80-f81446f1326c.png)
![ip address 2](https://user-images.githubusercontent.com/36437379/81631620-d45b7900-943a-11ea-9b61-54367ab2059f.png)

**Comment by ispysoftware** [comment] 2020-05-12 02:54
It's working fine here - what are you getting after you add in your local
IP?

**Comment by Jessicayanhu** [comment] 2020-05-12 02:56
It still returns reponse:
{"server":"iSpy","error":"Authentication failed","errorType":"authentication"}

**Comment by ispysoftware** [comment] 2020-05-12 03:03
you have an extra ? in your url at the beginning.

**Comment by Jessicayanhu** [comment] 2020-05-12 03:15
I remove the extra ?, but it still not work.
![new ip](https://user-images.githubusercontent.com/36437379/81634571-d07f2500-9441-11ea-8a78-7ecfc1a7f792.png)

returns error reponse:
{"server":"iSpy","error":"Authentication failed","errorType":"authentication"}

**Comment by ispysoftware** [comment] 2020-05-12 03:37
you are calling it from that IP address right? can you try
localhost:23000/getcontentlist... ?

**Comment by Jessicayanhu** [comment] 2020-05-12 03:40
I tried, but still not work...
![new ip localhost](https://user-images.githubusercontent.com/36437379/81636052-65cfe880-9445-11ea-9557-bfc1b51f7b0b.png)

**Comment by ispysoftware** [comment] 2020-05-12 03:53
Hmm pretty weird - you would only get that error if the IP address ispy is
seeing doesn't match the one you added.
You can add .* instead to make it accept all.
Try that - if that doesn't work check that a camera with ID 1 exists.
Failing that you'll need to run ispy in debug mode (build it from source)
and step through the localserver.cs code and figure out what the issue is.

**Comment by Jessicayanhu** [comment] 2020-05-12 12:33
Thank you for your suggestion, I will try it.

I have another two questions here.
1. Is there any command or query for "archive"? I want to save record files on my local server by HTTP or command line
<img width="249" alt="archive" src="https://user-images.githubusercontent.com/36437379/81690672-372a3000-948e-11ea-87d0-763a2a236489.png">

2.Is there any command or query for accessing record file? Not just play the record file, but get the  record file?

**Comment by ispysoftware** [comment] 2020-05-13 03:04
1) If you have archive instead of delete checked in settings then it will archive the file when you delete it.
2) check localserver.cs - you can use downloadclip.mp4

**Comment by Jessicayanhu** [comment] 2020-05-13 03:16
>>1.If you have archive instead of delete checked in settings then it will archive the file when you delete it.

How to check this setting? In which tab?

![settings](https://user-images.githubusercontent.com/36437379/81767474-194ee080-950b-11ea-8d48-982689c5fdbf.png)

**Comment by ispysoftware** [comment] 2020-05-13 05:05
storage tab, edit,
[image: image.png]

**Comment by Jessicayanhu** [comment] 2020-05-13 05:25
I can't see the image you pasted, could you please repaste it?

![address](https://user-images.githubusercontent.com/36437379/81774450-283e8e80-951d-11ea-8778-734c3740ac3f.png)

**Comment by ispysoftware** [comment] 2020-05-13 05:35
click on the storage tab under settings, edit the one entry and the option
to archive is on that control.

**Comment by Jessicayanhu** [comment] 2020-05-13 05:45
Thank you.
Can I archive a record mp4 file by using http request or command? Such as using  "localhost:23000/archive... " to archive a file?

**Comment by ispysoftware** [comment] 2020-05-13 06:23
no you'd need to add that yourself into the code

**Closed** 2020-07-09 01:40 UTC
